### PR TITLE
Provides Ansible v5.5.0 (ansible-core v2.12.3)

### PR DESCRIPTION
**Pull request by jotbe**

### CODE REVIEW

**Comment by jotbe** [comment]
@tknerr Have a look :)

**Comment by tknerr** [comment]
Oh nice, thanks @jotbe ! :)

Looks quite compact and clean, I would have expected that comes with syntax changes across all the yaml roles, but it seems that is not the case. Even better... :D

Let me get #28 in first though, so that we have a CI build for additional proof

**Comment by tknerr** [comment]
@jotbe #28 is in i.e. we now have a CI build running for the PRs. Mind rebasing your PR on top of master, so we can see the CI build succeeding here?

**Comment by jotbe** [comment]
@tknerr Rebased.

**Comment by jotbe** [comment]
@tknerr That one looks nice, even though it is the fork! :) If there are not other comments, feel free to merge.

**Comment by tknerr** [comment]
Sweet, thanks a lot @jotbe !!! 👍🏻 :)

**Pull request merged**
